name: Mirror and run GitLab CI
on:
  push:
    branches: [master]
jobs:
  to_gitlab_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: mono-colombia/mono-gitflow/github/actions/common/mirror-github-gitlab@main
        with:
          GITLAB_REPO: git@gitlab.com:mono-colombia/phoenix-alpine.git
          GITLAB_SSH_PRIVATE_KEY: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
